# Номер порта для соединения с сервером
port: 8082

# Имя эндпоинта
endpoint: "/wss"

# Режим проверки IP-адреса. Строгий (on) - только IP, нестрогий (off) - IP и порт
strictMode: "off"

# Максимальное количество соединений с одного IP-адреса
maxIpConnection: 1

# Таймаут для входящего соединения в миллисекундах
timeout: 5000

# Имя сервиса для отображения в логах
serviceName: "u-server"

# Уровень логирования
logLevel: "Debug"