# Номер порта для соединения с сервером
port: 8082

# Имя эндпоинта сервера
endpoint: "/wss"

# Количество соединений с сервером
connectionCnt: 10

# Интервал между соединениями в миллисекундах
connectionInterval: 100

# Таймаут для исходящего соединения в миллисекундах
timeout: 5000

# Имя сервиса для отображения в логах
serviceName: "u-client"

# Уровень логирования
logLevel: "Debug"